bots:
  unifood_telegram_bot:
    type: 'TELEGRAM'
    token: ''
    chat_chanel_id: '-'
    conditions:
      content_regex: '.*?'
      account_regex: '.*?'
    # only support in telegram
    # admin_ids can use /stopCron command
    admin_ids:
      - '5923714838'
  # caythueelo_discord_bot:
  #   type: 'DISCORD'
  #   token: '--'
  #   chat_chanel_id: '111'
  #   conditions:
  #     content_regex: '.*?'
  #     account_regex: '.*?'
webhooks:
  unifood_webhook:
    url: 'http://localhost:3001/api/payment/callback'
    token: '123456789:ABCDEF'
    conditions:
      content_regex: '.*?'
      account_regex: '.*?'

gateways:
  mb_bank_1:
    type: 'MBBANK'
    password: ''
    account: ''
    login_id: ''
    repeat_interval_in_sec: 10
  abc_bank_1:
    type: 'ACBBANK'
    password: '--'
    account: '123'
    login_id: 'abc'
    repeat_interval_in_sec: 10
